/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.g39.reto4.view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.g39.reto4.controller.ControllerRequerimientos;
import utp.misiontic2022.c2.g39.reto4.model.vo.Requerimiento_1;
import utp.misiontic2022.c2.g39.reto4.model.vo.Requerimiento_2;
import utp.misiontic2022.c2.g39.reto4.model.vo.Requerimiento_3;
import static utp.misiontic2022.c2.g39.reto4.view.ViewRequerimientos.controlador;

/**
 *
 * @author jfam
 */
public class FrmRequerimientos extends javax.swing.JFrame {

    /**
     * Creates new form FrmRequerimientos
     */
    public FrmRequerimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnR1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTablaR = new javax.swing.JTable();
        btnR2 = new javax.swing.JButton();
        btnR3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnR1.setText("Requerimiento 1");
        btnR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1ActionPerformed(evt);
            }
        });

        miTablaR.setAutoCreateRowSorter(true);
        miTablaR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(miTablaR);

        btnR2.setText("Requerimiento 2");
        btnR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2ActionPerformed(evt);
            }
        });

        btnR3.setText("Requerimiento 3");
        btnR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnR2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnR3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnR1)
                    .addComponent(btnR2)
                    .addComponent(btnR3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1ActionPerformed
        // TODO add your handling code here:
        
        String[] columnNombre = {"Fecha", "Id Compra", "Nom. Proveedor", "Pagado"};
        ControllerRequerimientos consulta = new ControllerRequerimientos();
        
        ArrayList<Requerimiento_1> listaR1;
        
        try {
            listaR1 = controlador.consultaRequerimiento_1();
            
            Object[][] datos = new Object[listaR1.size()][4];
            int index = 0;
            for (Requerimiento_1 r : listaR1) {
                datos[index][0] = r.getFechaCompra();
                datos[index][1] = r.getCodCompra();
                datos[index][2] = r.getNombreProveedor();
                datos[index][3] = r.getPagado();
                index++;
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            miTablaR.setModel(model);
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnR1ActionPerformed

    private void btnR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2ActionPerformed
        // TODO add your handling code here:
        String[] columnNombre = {"Fec. Inicio", "Ciudad", "Constructora", "Nom.Lider", "Codigo Tipo", "Estrato"};
        ControllerRequerimientos consulta = new ControllerRequerimientos();
        
        ArrayList<Requerimiento_2> listaR2;
        
        try {
            listaR2 = controlador.consultaRequerimiento_2();
            
            Object[][] datos = new Object[listaR2.size()][6];
            int index = 0;
            for (Requerimiento_2 r : listaR2) {
                datos[index][0] = r.getFecIni();
                datos[index][1] = r.getNombreCiudad();
                datos[index][2] = r.getNomConstructora();
                datos[index][3] = r.getNombreLider();
                datos[index][4] = r.getCodigoTipo();
                datos[index][5] = r.getEstrato();
                index++;
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            miTablaR.setModel(model);
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnR2ActionPerformed

    private void btnR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR3ActionPerformed
        // TODO add your handling code here:
        String[] columnNombre = {"Abrev."};
        ControllerRequerimientos consulta = new ControllerRequerimientos();
        
        ArrayList<Requerimiento_3> listaR3;
        
        try {
            listaR3 = controlador.consultaRequerimiento_3();
            
            Object[][] datos = new Object[listaR3.size()][1];
            int index = 0;
            for (Requerimiento_3 r : listaR3) {
                datos[index][0] = r.getAbrev();
                index++;
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            miTablaR.setModel(model);
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnR3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRequerimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnR1;
    private javax.swing.JButton btnR2;
    private javax.swing.JButton btnR3;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable miTablaR;
    // End of variables declaration//GEN-END:variables
}
